name: code_pulse
description: "Real-time algorithm visualizer that interprets code as text and animates data structures instantly"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^3.0.3
  # Code editor
  flutter_code_editor: ^0.3.5
  flutter_highlight: ^0.7.0
  flutter_riverpod: ^3.0.3
  highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true